### ISSUE TITLE
recommendation: commit vendor dir

### ISSUE THREAD

**Issue by pmorie** [shawn-hurley/osb-broker-k8s-lib#1]
...as proof against future repository name changes. I know this subject is a bit of a lightning rod for some folks, but it's the best way to ensure that a library keeps working for users.

**Comment by shawn-hurley** [comment]
I really don't like committing vendor for a library. I will lay out my case and if you are unconvinced then I'll add if it's needed to get merged into starter pack. 

1. A library is supposed to be vendored because of this, you usually don't want it to have a vendor directory anyway as it causes issues.
2. Most users of a library should be using a tool like `dep` or `glide` and that should handle the dependencies that the library declares it needs.
3. I think that it makes PRs that update dependencies much easier to review ex: https://github.com/pmorie/osb-starter-pack/pull/88


Those are my reasons if they are not convincing and you want vendor checked in for it to get merged into `osb-starter-pack` I will do that

**Comment by pmorie** [comment]
Your project, your rules :)
